theme: minima
title: Oct23Repo
header_pages:
  - projects.md
  - about.md
jekyll_comments:
  show_comments: "yes"
  allow_new_comments: "yes"
  comment_server: http://localhost:5001
  service_token: 84cdeefe07d14b5aaa9c10dea9cd05e6
